fix(GHA): Use Machine IP and add delay for latching (#59651)

diff --git a/.github/workflows/deploy-legacy.yml b/.github/workflows/deploy-legacy.yml
--- a/.github/workflows/deploy-legacy.yml
+++ b/.github/workflows/deploy-legacy.yml
@@ -80,11 +80,13 @@ jobs:
             UserKnownHostsFile=/dev/null
             StrictHostKeyChecking no" > ~/.ssh/config
           chmod 644 ~/.ssh/config
-
+          sleep 10
           for i in {1..3}; do
             TS_MACHINE_NAME=${TS_MACHINE_NAME_PREFIX}-api-${i}
-            tailscale status | grep -q "$TS_MACHINE_NAME"
-            ssh $TS_USERNAME@$TS_MACHINE_NAME "uptime"
+            tailscale status | grep -q "$TS_MACHINE_NAME" || { echo "Machine not found"; exit 1; }
+            sleep 1
+            MACHINE_IP=$(tailscale ip -4 $TS_MACHINE_NAME)
+            ssh $TS_USERNAME@$MACHINE_IP "uptime"
           done
 
       - name: Deploy API
@@ -134,7 +136,8 @@ jobs:
               pm2 save
               echo -e '\nLOG:Finished deployment.'
             "
-            ssh $TS_USERNAME@$TS_MACHINE_NAME "$REMOTE_SCRIPT"
+            MACHINE_IP=$(tailscale ip -4 $TS_MACHINE_NAME)
+            ssh $TS_USERNAME@$MACHINE_IP "$REMOTE_SCRIPT"
           done
 
   client:
@@ -251,11 +254,13 @@ jobs:
             UserKnownHostsFile=/dev/null
             StrictHostKeyChecking no" > ~/.ssh/config
           chmod 644 ~/.ssh/config
-
+          sleep 10
           for i in {0..1}; do
             TS_MACHINE_NAME=${TS_MACHINE_NAME_PREFIX}-${{ matrix.lang-name-short }}-${i}
-            tailscale status | grep -q "$TS_MACHINE_NAME"
-            ssh $TS_USERNAME@$TS_MACHINE_NAME "uptime"
+            tailscale status | grep -q "$TS_MACHINE_NAME" || { echo "Machine not found"; exit 1; }
+            sleep 1
+            MACHINE_IP=$(tailscale ip -4 $TS_MACHINE_NAME)
+            ssh $TS_USERNAME@$MACHINE_IP "uptime"
           done
 
       - name: Upload and Deploy
@@ -268,7 +273,8 @@ jobs:
             CLIENT_BINARIES=${{needs.setup-jobs.outputs.tgt_env_short}}-release-$CURRENT_DATE-${{ github.run_id }}
 
             echo -e "\nLOG:Uploading client archive to $TS_MACHINE_NAME..."
-            scp $CLIENT_SRC $TS_USERNAME@$TS_MACHINE_NAME:$CLIENT_DST
+            MACHINE_IP=$(tailscale ip -4 $TS_MACHINE_NAME)
+            scp $CLIENT_SRC $TS_USERNAME@$MACHINE_IP:$CLIENT_DST
 
             REMOTE_SCRIPT="
               set -e
@@ -318,5 +324,5 @@ jobs:
 
               echo -e '\nLOG:Finished deployment.'
             "
-            ssh $TS_USERNAME@$TS_MACHINE_NAME "$REMOTE_SCRIPT"
+            ssh $TS_USERNAME@$MACHINE_IP "$REMOTE_SCRIPT"
           done
